#!/bin/bash
#Ütleb kas arv on paaris või paaritu
echo -n "Sisesta suvaline täisarv:"
read taisarv
arv=$(($taisarv%2))
if [ $arv -eq 0 ]
then
echo "Antud arv on paaris"
else
echo "Antud arv on paaritu"
fi
