#!/bin/bash
#busside arvutamise skript
echo -n "Sisesta reisijate arv:"
read reisijad
echo -n "Mitu kohta on bussis:"
read kohad_bussis

#Arvutan mitu bussi tuleb täis
bussid=$(($reisijad/$kohad_bussis))
#echo "Täielikult täidetud on $bussid bussi/buss."

#arvutan mitu inimest ei mahtunud bussi
maha_jaanud=$(($reisijad % $kohad_bussis ))
if [ $maha_jaanud -ne 0 ]
then
bussid=$(($bussid + 1))
echo "Kokku on vaja $bussid bussi."
else
echo "Kokku on vaja $bussid täisbussi."
fi
